<?php

declare(strict_types=1);

namespace Misaf\DockerEngine\Api\V1_47;

final class Manifest
{
    public const string VERSION = '1.47';

    /** @var array<string, array{tag: string, method: string, path: string}> */
    public const array OPERATIONS = [
        'ConfigCreate'             => ['tag' => 'Config', 'method' => 'POST', 'path' => '/configs/create'],
        'ConfigDelete'             => ['tag' => 'Config', 'method' => 'DELETE', 'path' => '/configs/{id}'],
        'ConfigInspect'            => ['tag' => 'Config', 'method' => 'GET', 'path' => '/configs/{id}'],
        'ConfigList'               => ['tag' => 'Config', 'method' => 'GET', 'path' => '/configs'],
        'ConfigUpdate'             => ['tag' => 'Config', 'method' => 'POST', 'path' => '/configs/{id}/update'],
        'ContainerArchive'         => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/{id}/archive'],
        'ContainerArchiveInfo'     => ['tag' => 'Container', 'method' => 'HEAD', 'path' => '/containers/{id}/archive'],
        'ContainerAttach'          => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/attach'],
        'ContainerAttachWebsocket' => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/{id}/attach/ws'],
        'ContainerChanges'         => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/{id}/changes'],
        'ContainerCreate'          => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/create'],
        'ContainerDelete'          => ['tag' => 'Container', 'method' => 'DELETE', 'path' => '/containers/{id}'],
        'ContainerExport'          => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/{id}/export'],
        'ContainerInspect'         => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/{id}/json'],
        'ContainerKill'            => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/kill'],
        'ContainerList'            => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/json'],
        'ContainerLogs'            => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/{id}/logs'],
        'ContainerPause'           => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/pause'],
        'ContainerPrune'           => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/prune'],
        'ContainerRename'          => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/rename'],
        'ContainerResize'          => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/resize'],
        'ContainerRestart'         => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/restart'],
        'ContainerStart'           => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/start'],
        'ContainerStats'           => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/{id}/stats'],
        'ContainerStop'            => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/stop'],
        'ContainerTop'             => ['tag' => 'Container', 'method' => 'GET', 'path' => '/containers/{id}/top'],
        'ContainerUnpause'         => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/unpause'],
        'ContainerUpdate'          => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/update'],
        'ContainerWait'            => ['tag' => 'Container', 'method' => 'POST', 'path' => '/containers/{id}/wait'],
        'PutContainerArchive'      => ['tag' => 'Container', 'method' => 'PUT', 'path' => '/containers/{id}/archive'],
        'DistributionInspect'      => ['tag' => 'Distribution', 'method' => 'GET', 'path' => '/distribution/{name}/json'],
        'ContainerExec'            => ['tag' => 'Exec', 'method' => 'POST', 'path' => '/containers/{id}/exec'],
        'ExecInspect'              => ['tag' => 'Exec', 'method' => 'GET', 'path' => '/exec/{id}/json'],
        'ExecResize'               => ['tag' => 'Exec', 'method' => 'POST', 'path' => '/exec/{id}/resize'],
        'ExecStart'                => ['tag' => 'Exec', 'method' => 'POST', 'path' => '/exec/{id}/start'],
        'BuildPrune'               => ['tag' => 'Image', 'method' => 'POST', 'path' => '/build/prune'],
        'ImageBuild'               => ['tag' => 'Image', 'method' => 'POST', 'path' => '/build'],
        'ImageCommit'              => ['tag' => 'Image', 'method' => 'POST', 'path' => '/commit'],
        'ImageCreate'              => ['tag' => 'Image', 'method' => 'POST', 'path' => '/images/create'],
        'ImageDelete'              => ['tag' => 'Image', 'method' => 'DELETE', 'path' => '/images/{name}'],
        'ImageGet'                 => ['tag' => 'Image', 'method' => 'GET', 'path' => '/images/{name}/get'],
        'ImageGetAll'              => ['tag' => 'Image', 'method' => 'GET', 'path' => '/images/get'],
        'ImageHistory'             => ['tag' => 'Image', 'method' => 'GET', 'path' => '/images/{name}/history'],
        'ImageInspect'             => ['tag' => 'Image', 'method' => 'GET', 'path' => '/images/{name}/json'],
        'ImageList'                => ['tag' => 'Image', 'method' => 'GET', 'path' => '/images/json'],
        'ImageLoad'                => ['tag' => 'Image', 'method' => 'POST', 'path' => '/images/load'],
        'ImagePrune'               => ['tag' => 'Image', 'method' => 'POST', 'path' => '/images/prune'],
        'ImagePush'                => ['tag' => 'Image', 'method' => 'POST', 'path' => '/images/{name}/push'],
        'ImageSearch'              => ['tag' => 'Image', 'method' => 'GET', 'path' => '/images/search'],
        'ImageTag'                 => ['tag' => 'Image', 'method' => 'POST', 'path' => '/images/{name}/tag'],
        'NetworkConnect'           => ['tag' => 'Network', 'method' => 'POST', 'path' => '/networks/{id}/connect'],
        'NetworkCreate'            => ['tag' => 'Network', 'method' => 'POST', 'path' => '/networks/create'],
        'NetworkDelete'            => ['tag' => 'Network', 'method' => 'DELETE', 'path' => '/networks/{id}'],
        'NetworkDisconnect'        => ['tag' => 'Network', 'method' => 'POST', 'path' => '/networks/{id}/disconnect'],
        'NetworkInspect'           => ['tag' => 'Network', 'method' => 'GET', 'path' => '/networks/{id}'],
        'NetworkList'              => ['tag' => 'Network', 'method' => 'GET', 'path' => '/networks'],
        'NetworkPrune'             => ['tag' => 'Network', 'method' => 'POST', 'path' => '/networks/prune'],
        'NodeDelete'               => ['tag' => 'Node', 'method' => 'DELETE', 'path' => '/nodes/{id}'],
        'NodeInspect'              => ['tag' => 'Node', 'method' => 'GET', 'path' => '/nodes/{id}'],
        'NodeList'                 => ['tag' => 'Node', 'method' => 'GET', 'path' => '/nodes'],
        'NodeUpdate'               => ['tag' => 'Node', 'method' => 'POST', 'path' => '/nodes/{id}/update'],
        'GetPluginPrivileges'      => ['tag' => 'Plugin', 'method' => 'GET', 'path' => '/plugins/privileges'],
        'PluginCreate'             => ['tag' => 'Plugin', 'method' => 'POST', 'path' => '/plugins/create'],
        'PluginDelete'             => ['tag' => 'Plugin', 'method' => 'DELETE', 'path' => '/plugins/{name}'],
        'PluginDisable'            => ['tag' => 'Plugin', 'method' => 'POST', 'path' => '/plugins/{name}/disable'],
        'PluginEnable'             => ['tag' => 'Plugin', 'method' => 'POST', 'path' => '/plugins/{name}/enable'],
        'PluginInspect'            => ['tag' => 'Plugin', 'method' => 'GET', 'path' => '/plugins/{name}/json'],
        'PluginList'               => ['tag' => 'Plugin', 'method' => 'GET', 'path' => '/plugins'],
        'PluginPull'               => ['tag' => 'Plugin', 'method' => 'POST', 'path' => '/plugins/pull'],
        'PluginPush'               => ['tag' => 'Plugin', 'method' => 'POST', 'path' => '/plugins/{name}/push'],
        'PluginSet'                => ['tag' => 'Plugin', 'method' => 'POST', 'path' => '/plugins/{name}/set'],
        'PluginUpgrade'            => ['tag' => 'Plugin', 'method' => 'POST', 'path' => '/plugins/{name}/upgrade'],
        'SecretCreate'             => ['tag' => 'Secret', 'method' => 'POST', 'path' => '/secrets/create'],
        'SecretDelete'             => ['tag' => 'Secret', 'method' => 'DELETE', 'path' => '/secrets/{id}'],
        'SecretInspect'            => ['tag' => 'Secret', 'method' => 'GET', 'path' => '/secrets/{id}'],
        'SecretList'               => ['tag' => 'Secret', 'method' => 'GET', 'path' => '/secrets'],
        'SecretUpdate'             => ['tag' => 'Secret', 'method' => 'POST', 'path' => '/secrets/{id}/update'],
        'ServiceCreate'            => ['tag' => 'Service', 'method' => 'POST', 'path' => '/services/create'],
        'ServiceDelete'            => ['tag' => 'Service', 'method' => 'DELETE', 'path' => '/services/{id}'],
        'ServiceInspect'           => ['tag' => 'Service', 'method' => 'GET', 'path' => '/services/{id}'],
        'ServiceList'              => ['tag' => 'Service', 'method' => 'GET', 'path' => '/services'],
        'ServiceLogs'              => ['tag' => 'Service', 'method' => 'GET', 'path' => '/services/{id}/logs'],
        'ServiceUpdate'            => ['tag' => 'Service', 'method' => 'POST', 'path' => '/services/{id}/update'],
        'Session'                  => ['tag' => 'Session', 'method' => 'POST', 'path' => '/session'],
        'SwarmInit'                => ['tag' => 'Swarm', 'method' => 'POST', 'path' => '/swarm/init'],
        'SwarmInspect'             => ['tag' => 'Swarm', 'method' => 'GET', 'path' => '/swarm'],
        'SwarmJoin'                => ['tag' => 'Swarm', 'method' => 'POST', 'path' => '/swarm/join'],
        'SwarmLeave'               => ['tag' => 'Swarm', 'method' => 'POST', 'path' => '/swarm/leave'],
        'SwarmUnlock'              => ['tag' => 'Swarm', 'method' => 'POST', 'path' => '/swarm/unlock'],
        'SwarmUnlockkey'           => ['tag' => 'Swarm', 'method' => 'GET', 'path' => '/swarm/unlockkey'],
        'SwarmUpdate'              => ['tag' => 'Swarm', 'method' => 'POST', 'path' => '/swarm/update'],
        'SystemAuth'               => ['tag' => 'System', 'method' => 'POST', 'path' => '/auth'],
        'SystemDataUsage'          => ['tag' => 'System', 'method' => 'GET', 'path' => '/system/df'],
        'SystemEvents'             => ['tag' => 'System', 'method' => 'GET', 'path' => '/events'],
        'SystemInfo'               => ['tag' => 'System', 'method' => 'GET', 'path' => '/info'],
        'SystemPing'               => ['tag' => 'System', 'method' => 'GET', 'path' => '/_ping'],
        'SystemPingHead'           => ['tag' => 'System', 'method' => 'HEAD', 'path' => '/_ping'],
        'SystemVersion'            => ['tag' => 'System', 'method' => 'GET', 'path' => '/version'],
        'TaskInspect'              => ['tag' => 'Task', 'method' => 'GET', 'path' => '/tasks/{id}'],
        'TaskList'                 => ['tag' => 'Task', 'method' => 'GET', 'path' => '/tasks'],
        'TaskLogs'                 => ['tag' => 'Task', 'method' => 'GET', 'path' => '/tasks/{id}/logs'],
        'VolumeCreate'             => ['tag' => 'Volume', 'method' => 'POST', 'path' => '/volumes/create'],
        'VolumeDelete'             => ['tag' => 'Volume', 'method' => 'DELETE', 'path' => '/volumes/{name}'],
        'VolumeInspect'            => ['tag' => 'Volume', 'method' => 'GET', 'path' => '/volumes/{name}'],
        'VolumeList'               => ['tag' => 'Volume', 'method' => 'GET', 'path' => '/volumes'],
        'VolumePrune'              => ['tag' => 'Volume', 'method' => 'POST', 'path' => '/volumes/prune'],
        'VolumeUpdate'             => ['tag' => 'Volume', 'method' => 'PUT', 'path' => '/volumes/{name}'],
    ];

    /** @var array<string, string> */
    public const array SCHEMAS = [
        'ImageHistoryResponseItem' => 'ImageHistoryResponseItem',
        'Port'                     => 'Port',
        'MountType'                => 'MountType',
        'MountPoint'               => 'MountPoint',
        'DeviceMapping'            => 'DeviceMapping',
        'DeviceRequest'            => 'DeviceRequest',
        'ThrottleDevice'           => 'ThrottleDevice',
        'Mount'                    => 'Mount',
        'RestartPolicy'            => 'RestartPolicy',
        'Resources'                => 'Resources',
        'Limit'                    => 'Limit',
        'ResourceObject'           => 'ResourceObject',
        'GenericResources'         => 'GenericResources',
        'HealthConfig'             => 'HealthConfig',
        'Health'                   => 'Health',
        'HealthcheckResult'        => 'HealthcheckResult',
        'HostConfig'               => 'HostConfig',
        'ContainerConfig'          => 'ContainerConfig',
        'ImageConfig'              => 'ImageConfig',
        'NetworkingConfig'         => 'NetworkingConfig',
        'NetworkSettings'          => 'NetworkSettings',
        'Address'                  => 'Address',
        'PortMap'                  => 'PortMap',
        'PortBinding'              => 'PortBinding',
        'DriverData'               => 'DriverData',
        'FilesystemChange'         => 'FilesystemChange',
        'ChangeType'               => 'ChangeType',
        'ImageInspect'             => 'ImageInspect',
        'ImageSummary'             => 'ImageSummary',
        'AuthConfig'               => 'AuthConfig',
        'ProcessConfig'            => 'ProcessConfig',
        'Volume'                   => 'Volume',
        'VolumeCreateOptions'      => 'VolumeCreateOptions',
        'VolumeListResponse'       => 'VolumeListResponse',
        'Network'                  => 'Network',
        'ConfigReference'          => 'ConfigReference',
        'IPAM'                     => 'IPAM',
        'IPAMConfig'               => 'IPAMConfig',
        'NetworkContainer'         => 'NetworkContainer',
        'PeerInfo'                 => 'PeerInfo',
        'NetworkCreateResponse'    => 'NetworkCreateResponse',
        'BuildInfo'                => 'BuildInfo',
        'BuildCache'               => 'BuildCache',
        'ImageID'                  => 'ImageID',
        'CreateImageInfo'          => 'CreateImageInfo',
        'PushImageInfo'            => 'PushImageInfo',
        'ErrorDetail'              => 'ErrorDetail',
        'ProgressDetail'           => 'ProgressDetail',
        'ErrorResponse'            => 'ErrorResponse',
        'IdResponse'               => 'IdResponse',
        'EndpointSettings'         => 'EndpointSettings',
        'EndpointIPAMConfig'       => 'EndpointIPAMConfig',
        'PluginMount'              => 'PluginMount',
        'PluginDevice'             => 'PluginDevice',
        'PluginEnv'                => 'PluginEnv',
        'PluginInterfaceType'      => 'PluginInterfaceType',
        'PluginPrivilege'          => 'PluginPrivilege',
        'Plugin'                   => 'Plugin',
        'ObjectVersion'            => 'ObjectVersion',
        'NodeSpec'                 => 'NodeSpec',
        'Node'                     => 'Node',
        'NodeDescription'          => 'NodeDescription',
        'Platform'                 => 'Platform',
        'EngineDescription'        => 'EngineDescription',
        'TLSInfo'                  => 'TLSInfo',
        'NodeStatus'               => 'NodeStatus',
        'NodeState'                => 'NodeState',
        'ManagerStatus'            => 'ManagerStatus',
        'Reachability'             => 'Reachability',
        'SwarmSpec'                => 'SwarmSpec',
        'ClusterInfo'              => 'ClusterInfo',
        'JoinTokens'               => 'JoinTokens',
        'Swarm'                    => 'Swarm',
        'TaskSpec'                 => 'TaskSpec',
        'TaskState'                => 'TaskState',
        'ContainerStatus'          => 'ContainerStatus',
        'PortStatus'               => 'PortStatus',
        'TaskStatus'               => 'TaskStatus',
        'NetworkAttachment'        => 'NetworkAttachment',
        'Task'                     => 'Task',
        'ServiceSpec'              => 'ServiceSpec',
        'EndpointPortConfig'       => 'EndpointPortConfig',
        'EndpointSpec'             => 'EndpointSpec',
        'Service'                  => 'Service',
        'ImageDeleteResponseItem'  => 'ImageDeleteResponseItem',
        'ServiceCreateResponse'    => 'ServiceCreateResponse',
        'ServiceUpdateResponse'    => 'ServiceUpdateResponse',
        'ContainerSummary'         => 'ContainerSummary',
        'Driver'                   => 'Driver',
        'SecretSpec'               => 'SecretSpec',
        'Secret'                   => 'Secret',
        'ConfigSpec'               => 'ConfigSpec',
        'Config'                   => 'Config',
        'ContainerState'           => 'ContainerState',
        'ContainerCreateResponse'  => 'ContainerCreateResponse',
        'ContainerWaitResponse'    => 'ContainerWaitResponse',
        'ContainerWaitExitError'   => 'ContainerWaitExitError',
        'SystemVersion'            => 'SystemVersion',
        'SystemInfo'               => 'SystemInfo',
        'ContainerdInfo'           => 'ContainerdInfo',
        'PluginsInfo'              => 'PluginsInfo',
        'RegistryServiceConfig'    => 'RegistryServiceConfig',
        'IndexInfo'                => 'IndexInfo',
        'Runtime'                  => 'Runtime',
        'Commit'                   => 'Commit',
        'SwarmInfo'                => 'SwarmInfo',
        'LocalNodeState'           => 'LocalNodeState',
        'PeerNode'                 => 'PeerNode',
        'NetworkAttachmentConfig'  => 'NetworkAttachmentConfig',
        'EventActor'               => 'EventActor',
        'EventMessage'             => 'EventMessage',
        'OCIDescriptor'            => 'OCIDescriptor',
        'OCIPlatform'              => 'OCIPlatform',
        'DistributionInspect'      => 'DistributionInspect',
        'ClusterVolume'            => 'ClusterVolume',
        'ClusterVolumeSpec'        => 'ClusterVolumeSpec',
        'Topology'                 => 'Topology',
        'ImageManifestSummary'     => 'ImageManifestSummary',
    ];

    /** @var list<string> */
    public const array TAGS = ['Config', 'Container', 'Distribution', 'Exec', 'Image', 'Network', 'Node', 'Plugin', 'Secret', 'Service', 'Session', 'Swarm', 'System', 'Task', 'Volume'];
}
